// Backend type registry.
// Determines the request shape generated by post-json / put-json / delete-json.

export type BackendType = "rest" | "firebase" | "supabase" | "custom";

export interface BackendTypeDef {
  name: BackendType;
  authHeader: string;         // header name for token
  authPrefix: string;         // prefix before token value ("Bearer ", "")
  description: string;
}

export const BACKEND_TYPES: Record<string, BackendTypeDef> = {
  "rest":     { name: "rest",     authHeader: "Authorization", authPrefix: "Bearer ",  description: "Generic REST API" },
  "firebase": { name: "firebase", authHeader: "Authorization", authPrefix: "Bearer ",  description: "Firebase Realtime Database" },
  "supabase": { name: "supabase", authHeader: "apikey",        authPrefix: "",         description: "Supabase REST" },
  "custom":   { name: "custom",   authHeader: "Authorization", authPrefix: "",         description: "Custom header" },
};

export function isBackendType(name: string): boolean {
  return name in BACKEND_TYPES;
}

export function getBackendType(name: string): BackendTypeDef {
  return BACKEND_TYPES[name] ?? BACKEND_TYPES["rest"];
}
