import type { SuffixRule, PatternRule } from "../../grammar/types";

// ORDER MATTERS — longest suffix first.
export const SUFFIX_BLOCKS: SuffixRule[] = [
  { suffix: "-custom-select", blockName: "custom-select" },
  { suffix: "-bar-chart",     blockName: "bar-chart" },
  { suffix: "-line-chart",    blockName: "line-chart" },
  { suffix: "-donut-chart",   blockName: "donut-chart" },
  { suffix: "-color-bar",     blockName: "color-bar" },
  { suffix: "-select",        blockName: "select" },

  { suffix: "-page",      blockName: "page" },
  { suffix: "-row",       blockName: "row" },
  { suffix: "-column",    blockName: "column" },
  { suffix: "-card",      blockName: "card" },
  { suffix: "-box",       blockName: "box" },
  { suffix: "-wrapper",   blockName: "wrapper" },
  { suffix: "-container", blockName: "container" },
  { suffix: "-section",   blockName: "section" },
  { suffix: "-header",    blockName: "header" },
  { suffix: "-footer",    blockName: "footer" },
  { suffix: "-info",      blockName: "info" },
  { suffix: "-content",   blockName: "wrapper" },
  { suffix: "-group",     blockName: "wrapper" },
  { suffix: "-bar",       blockName: "wrapper" },
  { suffix: "-field",     blockName: "input" },
  { suffix: "-icon",      blockName: "icon" },
  { suffix: "-text",      blockName: "text" },
  { suffix: "-image",     blockName: "image" },
  { suffix: "-avatar",    blockName: "avatar" },
  { suffix: "-button",    blockName: "button" },
  { suffix: "-label",     blockName: "text" },
  { suffix: "-link",      blockName: "link" },
  { suffix: "-title",     blockName: "title" },
  { suffix: "-toggle",    blockName: "toggle" },
  { suffix: "-dropdown",  blockName: "dropdown" },
  { suffix: "-video",     blockName: "video" },
  { suffix: "-name",      blockName: "text" },
  { suffix: "-handle",    blockName: "wrapper" },
];

export const PREFIX_BLOCKS: string[] = [
  "text-", "title-", "button-", "icon-", "image-", "logo-",
  "avatar-", "link-", "label-", "input-", "toggle-", "slider-",
  "checkbox-", "radio-", "select-", "custom-select-",
  "badge-", "divider-", "video-", "row-", "column-", "card-",
  "sidebar-", "accordion-", "tabs-", "modal-", "table-",
];

export const PATTERN_BLOCKS: PatternRule[] = [
  {
    regex: /^every-(\d+)-(second|seconds|minute|minutes|hour|hours)$/,
    blockName: "timer",
    note: "Interval = numeric group; unit = unit group.",
  },
  {
    regex: /^(below|above|left-of|right-of)-.+$/,
    blockName: "position-hint",
    note: "Modifier on target element name.",
  },
  {
    regex: /^page-\d+$/,
    blockName: "page",
    note: "Numbered pages — allowed exception to no-trailing-number rule.",
  },
  {
    regex: /^keep-.+$/,
    blockName: "keep-span",
    note: "INTERNAL — generated by remember/recall actions.",
  },
];
